CREATE TABLE IF NOT EXISTS urna_logs (
	id VARCHAR (30) PRIMARY KEY NOT NULL,
	modelo VARCHAR (10) NOT NULL,
	total_votos INTEGER NOT NULL,
	turno SMALLINT NOT NULL,
	estado VARCHAR (5) NOT NULL,
	municipio SMALLINT NOT NULL,
	zona SMALLINT NOT NULL,
	secao SMALLINT NOT NULL
);

CREATE TABLE IF NOT EXISTS secao (
	id VARCHAR (30) PRIMARY KEY NOT NULL,
	estado VARCHAR (5) NOT NULL,
	municipio SMALLINT NOT NULL,
	zona SMALLINT NOT NULL,
	secao SMALLINT NOT NULL,
	turno SMALLINT NOT NULL,
	modelo_urna VARCHAR (10) NOT NULL,
	quantidade_eleitores INTEGER NULL,
	abstencao INTEGER NULL,
	total_votos INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS voto (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	secao_id VARCHAR (30) NULL,
	modelo_urna VARCHAR (30) NULL,
	cargo VARCHAR (30) NOT NULL,
	candidato INTEGER NOT NULL,
	partido INTEGER NOT NULL,
	total_votos INTEGER NOT NULL
);
